[colors.primary]
background = "#25282c"
foreground = "#e0e2e8"
dim_foreground = "#ecd7db"
bright_foreground = "#e0e2e8"

[colors.cursor]
text = "#25282c"
cursor = "#ffb0cd"

[colors.vi_mode_cursor]
text = "#25282c"
cursor = "#e0e2e8"

[colors.search.matches]
foreground = "#25282c"
background = "#73342b"

[colors.search.focused_match]
foreground = "#25282c"
background = "#ffb4a9"

[colors.footer_bar]
foreground = "#ecd7db"
background = "#3a3e42"

[colors.hints.start]
foreground = "#25282c"
background = "#713341"

[colors.hints.end]
foreground = "#25282c"
background = "#713341"

[colors.selection]
text = "CellForeground"
background = "#713341"

[colors.normal]
black = "#25282c"
red = "#ffb0cd"
green = "#aad291"
yellow = "#edc06c"
blue = "#a6c8ff"
magenta = "#e0b8f6"
cyan = "#89d6b9"
white = "#ecd7db"

[colors.bright]
black = "#9d8c90"
red = "#ffd9e4"
green = "#c5efa7"
yellow = "#ffdea7"
blue = "#d5e3ff"
magenta = "#f4daff"
cyan = "#a4f2d5"
white = "#e0e2e8"

