[colors.primary]
background = "{{tm.background}}"
foreground = "{{tm.foreground}}"
dim_foreground = "{{on-surface-variant}}"
bright_foreground = "{{on-surface}}"

[colors.cursor]
text = "{{tm.background}}"
cursor = "{{tm.caret}}"

[colors.vi_mode_cursor]
text = "{{tm.background}}"
cursor = "{{tm.foreground}}"

[colors.search.matches]
foreground = "{{tm.background}}"
background = "{{tm.find-highlight}}"

[colors.search.focused_match]
foreground = "{{tm.background}}"
background = "{{tm.find-highlight-foreground}}"

[colors.footer_bar]
foreground = "{{on-surface-variant}}"
background = "{{surface-container-highest}}"

[colors.hints.start]
foreground = "{{tm.background}}"
background = "{{tm.selection}}"

[colors.hints.end]
foreground = "{{tm.background}}"
background = "{{tm.selection}}"

[colors.selection]
text = "CellForeground"
background = "{{tm.selection}}"

[colors.normal]
black = "{{ansi.blk}}"
red = "{{ansi.red}}"
green = "{{ansi.grn}}"
yellow = "{{ansi.yel}}"
blue = "{{ansi.blu}}"
magenta = "{{ansi.mag}}"
cyan = "{{ansi.cya}}"
white = "{{ansi.wht}}"

[colors.bright]
black = "{{ansi.gra}}"
red = "{{ansi.rrd}}"
green = "{{ansi.ggn}}"
yellow = "{{ansi.yyl}}"
blue = "{{ansi.bbl}}"
magenta = "{{ansi.mmg}}"
cyan = "{{ansi.ccy}}"
white = "{{ansi.wwt}}"

